### PR TITLE
Documenting features

### PR DESCRIPTION
**Pull request by vegerot**

### CODE REVIEW

**Comment by cc-wr** [comment]
@vegerot, even after #70, the formatting for `README.md` does not seem to be quite right. Can you remove all the leading whitespace on line 25?

**Comment by cc-wr** [comment]
(I'll merge this at the same time as `feature/jupyter-console-support`.)

**Comment by arnoudbuzing** [comment]
When will this be merged?

**Comment by cc-wr** [comment]
A general request for comments on #71 is at #82.

**Pull request merged**
